# Generated by Django 3.2 on 2021-05-09 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_blogpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 5, 9, 10, 18, 10, 848099, tzinfo=utc), upload_to='media'),
            preserve_default=False,
        ),
    ]
