# Generated by Django 3.2 on 2021-05-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogpostcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
