# Generated by Django 3.2 on 2021-05-10 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210510_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
