# Generated by Django 3.2 on 2021-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210511_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
