# Generated by Django 3.2 on 2021-05-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
