# Generated by Django 3.2 on 2021-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_new_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='source',
        ),
        migrations.AlterField(
            model_name='new',
            name='subtitle',
            field=models.CharField(max_length=200),
        ),
    ]
