# Generated by Django 3.2 on 2021-05-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_new_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='source',
            field=models.CharField(max_length=500),
        ),
    ]
