# Generated by Django 3.2.3 on 2021-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210517_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='eventMedia')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
