# Generated by Django 3.2.3 on 2021-08-04 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_bannerevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerevents',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
